### ISSUE TITLE
good work

### ISSUE THREAD

**Issue by furesoft** [ed-cooper/Ebnf.Compiler#1]
good work, but could you provide more Samples?

like parsing an lisp file

**Comment by ed-cooper** [comment]
Hi,
Whilst I agree that the current example is slightly limited, I believe that it amply demonstrates the range of syntax supported by this implementation.
My other reasoning is that limitations in this implementation (e.g. no possibility of extending the parser through something like a TokenBeginParse event) make it largely unsuitable for more complex languages like Lisp, especially when much more mature solutions (like Antlr, which I highly recommend) exist.
If you submit a pull request however adding this documentation I will be happy to review it.
